name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ${{ GITHUB_REPOSITORY }}
      uses: actions/checkout@v1
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Install dependencies
      run: yarn install
    
    - name: Test banangram-frontend
      run: |
        cd packages/bananagram-frontend
        yarn test:ci
