name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Check commits in Pull Request contain Issue reference
      if: github.event_name == 'pull_request'
      uses: jedster1111/pr-lint-action@GH-1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Install dependencies
      run: yarn install
    
    - name: Test banangram-frontend
      run: |
        cd packages/bananagram-frontend
        yarn test:ci
